language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: IdzN9a9s56urENGpNZWAyaYE2nO0VsmyD0zEDhw9l7WjSUMwtcGpfLEGubbP8Vf/dyWXQAttOZ7zT9oJsZfXg9TazmWEssjtCB2r1IdGGNTQQ2i23AdxBUFAH4VDNSXsS82U5u1lKBgFcd5K3Y7dEYGjB1Iv9RyWTz/FXMa6BL/uQwANa6HFYpw/ELOYAfdImdlIwRRltw6Pn3HBf7REX/qFRpwmhbaq1OEZR82zSA9JMKSIXe4Fqvl/gsjuRy8vRZ1hiImVrgZMmqdjT6CN1VJbUXKIEfG+rcDR1A58A21W6G2Sif+NR3rTUNkAqmBg50DmX82NdCiRE3jKnLNCyNiWE9R/7dUlUf8p1cI7O6IhsGK74QDltfKYb6RNRmtX/A0K1prgpCvAvfEes/IQKhCQxlXsYJ/D631P8Euffsyria1brwcGvc4Uymtff7B45aPa6XEyLjU0XvJLyBOb7UQ6hfOU3dte/MT3qvtaddeVtnTFMnxLDZy5589+X4O6nqjjFR/c8dvxvjQLt3os8OJpUvtmVMKN5yx+lBAcDIAzH4M3QOnJc2Ji9YMO+ciMszRL6pt7MkPFFF4Th0VVphYzPAXa1qWHvGLJhjHhap0n6mfzeTYOeu3vGKEhGPV33OUv40noyNnZZEwZFoB7YOXmBoWNnxAzgn4csm4L3HQ=
env:
  global:
  - secure: YIv7tSslarWhCMPGL00iSJNiciEtqcoQpZau6wAiK+E1cIwfRstH/sonjK1qLK7727y1WNsfzKm+JNm1s2K54GrmSH5HXFNUskO3VUtx2whs3FT3sRT2YCFXaE3VV/sN7K3JPVRsiyycJ8BVFTVKqgdaQLbV6qr/VFZGCECWlNRJnmRznibGImIN8FyXZNj2LzKZdVeaTV24NP5TRoH0Sk4us5T9CFf1ywjhpsjVFopiElNWfcQLqsFm6xwUvKPpgpwJQ09/7zJgJe0tx31oJu+TbVTsM5COj/St+j823TxXJpo+z86EmwTAnDslELLRicLh3ZAZ0hOBq+98t0LFzkRrDehxQV08+tZ3fhv2bJIC63jxh6shi41xKeJBd40ZverH0WPvBOJJeAu01eCUxSBQpjIGUQD8ynHcnWAl0pCNFmyL6zefqgagndEFh4rxUl5nq9Vz7kGInlNeWegZIEURVYy0c+uZz/344pMpxRD8ULPZCYhZZZz1KYCsiMbWfKXlUGeKqA0rS4TbMk2NZKBXQXqQuU9z5CToL1oCfhakzPwvRj0QOG/cXNY2Ga0BEmOQroCUE54KDcdOBrq6NNfxfXBvqgq2ocKIKs/aTq24TNWlzJMAu+YO+yuGUQsGbXbfLaRfYKryOjrx+tATlIQJR4tUTnkSOT1/X4oGSCs=
  - secure: swQ2uVdXRVDi7P7kLoW04SWnf5v3j/izVYRyO1DNBPwz1Iaz6f0HMfTGbB33f6d2cL3WTIa2PLA1wPT4LHkt8Yt+NtKM0q41x5loMGHXXhKwtznngDtvO31Ja4YPUTFsgHgfNuh4WSHTuzkum53VK/b3jROYxv0/inecRKx0pkWIeiAgplTZJ04xz/90DgevWWCTvaTB1r46cP9UfN0Yf8r+gJhVS5XE6gNi8Mw/pUM2/dbxhneCGZeABcuE5pCkTz/DgYsEv9upVfMHNVeSgj0UO1EYeZJxA3+FGHGP5iBgptEbhlWXjufOlCZeqzLuLx+1b7aew4TNBcr8yhGmLBcUe/zYtdMQFV8+bjNhOLLQKhCcse/g5qKPmdZBQE4UfNtEbmVw2BIyDiEhqbWus1NRnxt766kgFchFFtf68X84wULWVAb5d/xE1OqQ33HJYda3JnocMGrLzusUk5n+/hLP4BqV8B6IUDnT7SB9po/8p6+QVhko2RXNhyD/TVeTlz7pwBVT2VcOWZFw/yBJBLzjuBIwLEA42QIGybuPaKbtzjgwOhCDAolOfw+14y89OaCtdWCzKmpvBK4n2BVNiWHwTWIpQ4trdsJtJIa/8I5O1Uu87pBdTWTYuRFuQitGWvRbqk4kx/imfZ8UY3XzEOPFMi7asjXrS51MqiKmJ9E=
  - secure: HcykLO1cQpmStidC0S4YgfV19u9VJWnHHlix960E85ki7AWcrzsTH7LbBd9dqmhxsYc74W9iQWPgDBUz+wc3R5bmf6LzFE5LFKWpPxXHiLwB9eecvczY3H7Q7IRPGZzjRm4Q8fqWHTm9eQhBx4jiLTR6KR7LAGBXFAGaLV+qrYmACYGGiybGhcOx9aTP7TGDPBsxsCg+kD3ZN25t/uXwfi2nLa3Qyz8fv+yao7muRRnugXeehktXpzYcS5Ba/DvUKhf0eRKhGTHkrgA/DAemyddmqLr/zL9ssfa4fhGsDnhaeJ1D4l0xIL/qh0SGRl609yEQvnpHOrX+rJg0Bybz2YyqieWW86RnxkI3Y/v2BmZY3IvLtq7dbuaLGzhzIbHGJf63jfTQqDc6KRb6VZLNik5bHfsea/+VP7v935DBez9JKLFcId5w6rVwb2QUC+FF6n0mA1C2Z+/IJZlvX+wzU1d9Bd+6w1aDvqYIFid0lP6vq3TjZYf55cdBRV/I20Spn+oeDuula6Y/pBFexRRR16rV4YuYN3Aev+JZJNQ8GdkLgeT/Y5r9wF8tmPJQOaeRCjcs+Fqttg6UW2amcS57WWGeMztEodDz/CMtKIwlt3WJ8uftvVC/Rhzo5zfsiwIOsKellAtlsF8HRqDx2WbeGGiYhoSncLrJJtncR7bgC1o=
before_install:
- openssl aes-256-cbc -K $encrypted_62508508b78f_key -iv $encrypted_62508508b78f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- ls -la
