language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: FlNOsnuhDrPreYRY5qY982PUo9Mo+QmkO4+mgBd1bEwnKJw/FYNkMDSEJItrv/unQyzsUoBbHrN3vGdGlKoJpejnkXk/RJPfXJ8B+VN6rGnSBZAtiZXCiKPwZ/8Ft9o4fnoce3EFKPPnE6GDJ9nODoXfqS+gYjuTRHTdpkuYn4sgk3LEDbFit9X/DIvq0pEPgoE09cLX2RhzF75ohDegKUqzRqRfwq8powv8tGoqYRJ0KlCLZcHEzaV2SA7ZbvTsNO2OYjZ2Lne73hjUUaZNhJAo14TmQ9EyrjXvQI+Ycd9UYt/Hdvta8GEHu2Hhee3rzrLlnLQZglLiHhcsYHrO078Ma4ia6gMIZBwn7sg3KVkA6TILpJvXNIaSOID7ypKpNx1Vy4u51chJSA84Xl9MRf0cXrJBQWXxE3Pd0PS9yi0D4tfSMcTHeYDuK/IuRI/nsQIWSeTWQzdtJ/GCsOCvBfS1nxE01PwHjn+GRJWsLyDLmDI+kd+PF40niiMeF0tOJA+IoeBtn629ysjsdgxFXtBrmfDPM3PTaAtYvusUJlRnk7ElPphbsweDqLpNgNNTI/K6ww2Txm14mUOeY4vHyuIqMH6izpteEv/pGeD+7sZBTzFu3lHpIO9OYfP93Ni0XGqdK2fiYjgjQdIB2QYc49ZqhiVtj2mng1IIa/GST84=
  - secure: 6OMMN4OmIaALguZRMNFZx9j5uCdBGNyIrIcmE15XkH02IgsFlc4AYKMRunAIf5gcN4LeT8DI66DB0j4vQC783rMhs3ej4jdgeThRNZh8UYt4EHC/jMZkJ8v59zCp+6BcSQ359t4FrZHqD9XEJNtCLKND3e2drfVsuaOxrsZGq5TDxOPsVnemp+PbjV47Bf7fY8OiMNBVyLXJF1f72r855dTjgXnYfRMC1uRfWq3/s2FLNpeAcmBzB0yTP6QVDKJquI35R49OwiQIc5tCB7dQEq9FaXDZda/P32+8pqXTOTy0ZKDJCBp3eFX42hqg9+d9ZLb9PiUXzt8H8EpzIajtu9fLybfIFIrQEcLCiyCJktxONZFNufK4fQhMkqRUt/ZsbxiidLgMjk40E3Ls+lbZUL91WuAEpRs/je07Mhz2b5N94K4TycpSSdwk69UDh/gTQrRx0MXbmVbyxK0q+fZmdBdhwUAVR4q31BLR7EasKWT0uH5UJxZ1A4r5F4bqHZeFKSWrNYvn3aRxy/Ppaq7Ttcy0nzvPhs8sEcLx40hBchNjccqjPTLLuQvHCsAmN2UAJtuxCvYFWkeIdbklHloihwsdLpdSjJPAeEh9E50aheEz7vmktprKbW/tOEpqqHd2aYELvZUpWGIAyf9M2WU7jtvfGOGvp3Faod18FI8Q6Xo=
before_install:
- openssl aes-256-cbc -K $encrypted_62508508b78f_key -iv $encrypted_62508508b78f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine* /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine*

notifications:
  slack:
    rooms:
      secure: IdzN9a9s56urENGpNZWAyaYE2nO0VsmyD0zEDhw9l7WjSUMwtcGpfLEGubbP8Vf/dyWXQAttOZ7zT9oJsZfXg9TazmWEssjtCB2r1IdGGNTQQ2i23AdxBUFAH4VDNSXsS82U5u1lKBgFcd5K3Y7dEYGjB1Iv9RyWTz/FXMa6BL/uQwANa6HFYpw/ELOYAfdImdlIwRRltw6Pn3HBf7REX/qFRpwmhbaq1OEZR82zSA9JMKSIXe4Fqvl/gsjuRy8vRZ1hiImVrgZMmqdjT6CN1VJbUXKIEfG+rcDR1A58A21W6G2Sif+NR3rTUNkAqmBg50DmX82NdCiRE3jKnLNCyNiWE9R/7dUlUf8p1cI7O6IhsGK74QDltfKYb6RNRmtX/A0K1prgpCvAvfEes/IQKhCQxlXsYJ/D631P8Euffsyria1brwcGvc4Uymtff7B45aPa6XEyLjU0XvJLyBOb7UQ6hfOU3dte/MT3qvtaddeVtnTFMnxLDZy5589+X4O6nqjjFR/c8dvxvjQLt3os8OJpUvtmVMKN5yx+lBAcDIAzH4M3QOnJc2Ji9YMO+ciMszRL6pt7MkPFFF4Th0VVphYzPAXa1qWHvGLJhjHhap0n6mfzeTYOeu3vGKEhGPV33OUv40noyNnZZEwZFoB7YOXmBoWNnxAzgn4csm4L3HQ=
