language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: IdzN9a9s56urENGpNZWAyaYE2nO0VsmyD0zEDhw9l7WjSUMwtcGpfLEGubbP8Vf/dyWXQAttOZ7zT9oJsZfXg9TazmWEssjtCB2r1IdGGNTQQ2i23AdxBUFAH4VDNSXsS82U5u1lKBgFcd5K3Y7dEYGjB1Iv9RyWTz/FXMa6BL/uQwANa6HFYpw/ELOYAfdImdlIwRRltw6Pn3HBf7REX/qFRpwmhbaq1OEZR82zSA9JMKSIXe4Fqvl/gsjuRy8vRZ1hiImVrgZMmqdjT6CN1VJbUXKIEfG+rcDR1A58A21W6G2Sif+NR3rTUNkAqmBg50DmX82NdCiRE3jKnLNCyNiWE9R/7dUlUf8p1cI7O6IhsGK74QDltfKYb6RNRmtX/A0K1prgpCvAvfEes/IQKhCQxlXsYJ/D631P8Euffsyria1brwcGvc4Uymtff7B45aPa6XEyLjU0XvJLyBOb7UQ6hfOU3dte/MT3qvtaddeVtnTFMnxLDZy5589+X4O6nqjjFR/c8dvxvjQLt3os8OJpUvtmVMKN5yx+lBAcDIAzH4M3QOnJc2Ji9YMO+ciMszRL6pt7MkPFFF4Th0VVphYzPAXa1qWHvGLJhjHhap0n6mfzeTYOeu3vGKEhGPV33OUv40noyNnZZEwZFoB7YOXmBoWNnxAzgn4csm4L3HQ=
env:
  global:
  - secure: yHi4LQepms1N33i629vAEFWwEW0Bi8VOSe0BY++z6gu41HATLfSzdfABbkfRvgajxkocAMZ6jfc9PxHmIiAYTfgxWqsdRmYJwdwlxs7vQ4AQbpVUotIO+SZAvkM9Sc3+PGUDlThiHRnUIQ6WcqMdaKKqJ49WZxuOWPp+klMeD0O9PVe8FHWwPjLkY5fWjI6t/tPJK2RkQmLJvkIfRgIMAxytfDPGvZadChxT2Ld0N8ufqAXjK2Ml5Ckvtf4iXYRkIvceDdQJ6qdryxhYUjpmDusku3bHODWU8SQrrRLMnnHAkZ0rDKhORb0QWcwkWEy2XKorRy5Bgtt8ynyHYtZYvc8KvekuUcFkaFTk3FOIO7yUdw75iVPWQ4WPutzi5Y7OLDjyp8+QZgZBBPeBGxzHtTD5oRVic9h284ou066tGqcRXEG+y8KVoy66dG19UcouiE8jlxLmnFTlXKPRVhcce66M4au5/AgmA7ePOujMxYVp3JvQ6ApHaNCk1wtpGljir8RKWmK44KNEg3WNYD1v1kcajeAJOdGXJ0uVCRnH2vIQhgbh3hqc7JG7QzWn2muedZm8vL0HAiGkw9eWvjJCSHVjeCumUazn/tNujD7h/pvJdrcB7rzL1qRkOmNNmVmAORKPuHLlfoED6/owNlQxhXQd1KhIHGJKQQCqkkmPMc0=
  - secure: JWI8SP7DOhq2mZLswzutf+VsfJPaGeun3kle5AyAelmkrFpsN+AKNHJRVN6OncYaLUMW2BYQ7zK+K3ORdPWQSr/VtWkuqViHO22JnVZ4LV/Tls7OLILl/lBHIFYtf2SZbV51UDr4vbjEZXcD31q9znqOAeCP7nMMV/clvN43dUBc9+ZxD3MFaum5xrvf+sGxpiNHYnQS6/blYZBE8rqIitF5gSV16KD+w0awZsffzoydFl0VkcmlRsfdnTt8obL1H7mrvrsuh0Y1JhmbaRJbzm3vGQAGzwOxDVSIkgYCNXckZ+/Em7BajydfRFtE1HPUDBahUjWPC8+tJFAb7cNlZ5IL/P+xJzw39628vGbhpngt76pDeWT/WuC+NsM9zkDSjN9hx/ZmuRsl5fmNiSk91sJg6v57OgeaaFso0zGhkfnm9VRdk1zisZNuemg1d8jwUA0G7WiFpEoIyQczg1rPQEexXyGvOyE/vu4XCYNUvRJCq5EyzlHqSi5TJohANnRBToIzET5JZbQonoltnGth4V9XeW1z/1pAQvPYggrYWI9/JeB30dglTUkETqVnfm5q/LgmGJff9ewJqbcqgKibrLUgZHhDXYkpF+EkCSFUtBpPdgb/c0zvd5YxT7hQlOqi1LN2mXHBoCZ7csMtScGOwmiRrPwswT8hymdWLznmPyk=
  - secure: LkRcZZERAC6nhEh8D1S+dYD4fThNVAUHl9MQ6PcODyeiP0tCosmlm4bBpRu8O2uy2afQNmvByRreMelwpCvptA04URjfPKck97HsBVbGUJMeSq/B13/smvkDaauOmtB+Sj1R4X6fCLeKAZJxEALJ4dAnhdcfe1AfTf2eESNFuRHlaWPH5OoqW3tG4Gx8Oo0ARSzV3lAtE2Papr5X4UI9z7uHw5QJdT3/YI70JCg5J0YaJbflrjyRptfSNbYd+9tMX7S9vb6F2GZF/TRgAqfqTxhbhYgXEH5aTlJqjWfv8i/hsiwRhpocjUu2/cxRZJW0T8qTBR2v1X+OSgZxSx1MuR+8udRgrz+1k6TX3T7m+PKGLrDa8XQfp7ekmbSuKsjL04pwUsX3Dm4JSvzXKpohWN1z+QDubXCXpzxohb6Vgx5oyB8lZEdX2tmPr3/GtDVdyM91/S9dyGiNhEtWdQ2/ZUkXN8ULTnXGF2FQaX1uJY6RrxnHpaNJRp91la3euwFi69FAIsyivQTzQwrqEw5nNG2/TZfaF1DU/svWdy6uQlylKMJFGxbTEJqCm3JVRV086mLrQZnZsARff6FbdZQo/7XeMnUrG39/SwpePAfGrSSGltHmUJlya64UtpXF2LLGBgiu+uCThPFo/739FvlDiZCKTeSnb99TZAYz5fB07Bo=
before_install:
- openssl aes-256-cbc -K $encrypted_62508508b78f_key -iv $encrypted_62508508b78f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- ls -la
